"use client";
import { useState } from "react";

type Module = { title: string; subtitle: string; overview: string; topics: string[] };
const modules: Module[] = [
  { title: "Modalidades de viagem de animais", subtitle: "PETC, AVIH, AVI e situações especiais", overview: "Entenda as modalidades de transporte, seus limites operacionais e os critérios para orientar cada caso.", topics: ["Cabine: PETC", "Bagagem acompanhada: AVIH", "Carga viva: AVI", "Cão de serviço e suporte emocional", "Embarque por liminar"] },
  { title: "Exigências sanitárias internacionais", subtitle: "Como interpretar regras por destino", overview: "Aprenda a consultar acordos sanitários, Import Permit, notificação de chegada, respaldo, sorologia e requisitos por país.", topics: ["Países com acordo sanitário", "Import Permit e notificação de chegada", "Respaldo sanitário", "Sorologia e laboratórios credenciados", "Quadro-resumo de emissão de CVI"] },
  { title: "Assessoria técnica e planejamento", subtitle: "Do diagnóstico à viagem", overview: "Transforme destino, rota, modalidade e prazos em um planejamento seguro e compreensível para o tutor.", topics: ["Análise de destino e rota", "Avaliação de risco", "Comunicação com o tutor", "Cronograma sanitário", "IATA e IPATA"] },
  { title: "Bolsas e caixas de transporte", subtitle: "Conforto, segurança e compatibilidade", overview: "Conheça critérios de medição, requisitos de caixa, restrições e a escolha adequada para cada modalidade.", topics: ["Como medir corretamente o pet", "Padrões IATA", "Ventilação e segurança", "Restrições e erros comuns", "Bolsa para PETC"] },
  { title: "Documentação veterinária e emissão do CVI", subtitle: "Conferência e certificação internacional", overview: "Organize documentos, confira identificações e compreenda os fluxos de CVI presencial e e-CVI.", topics: ["Carteira de vacinação e microchip", "Conferência da sorologia", "Responsabilidade técnica", "CVI presencial e online", "Cadastro e emissão no e-CVI"] },
  { title: "Gestão e precificação do serviço", subtitle: "Valor técnico da atuação", overview: "Estruture a consultoria, comunique o escopo e precifique o trabalho que acontece antes, durante e depois da emissão.", topics: ["O que está sendo vendido", "Consulta clínica e certificação", "Formação de valor", "Serviços complementares", "Boas práticas de precificação"] },
];
const checklist = ["Passageiro pet confirmado", "Caixa ou bolsa de transporte adequada", "Reserva do pet confirmada", "Carteirinha de vacinação original", "CVI emitido", "Documentação conferida", "Identificação e contatos atualizados"];

export default function Home() {
  const [active, setActive] = useState(0); const [tool, setTool] = useState(false); const [checks, setChecks] = useState(checklist.map(() => false));
  const current = modules[active];
  return <main className="reader"><header className="reader-header"><a className="brand" href="#top"><span>e</span>embarpet</a><p>DO ZERO AO CVI · APOSTILA DIGITAL</p><button type="button" onClick={() => window.print()}>Baixar em PDF</button></header><div className="reader-layout" id="top"><aside className="sidebar"><p className="side-label">SUMÁRIO DA APOSTILA</p>{modules.map((module, index) => <button className={!tool && active === index ? "nav-item active" : "nav-item"} onClick={() => { setActive(index); setTool(false); }} key={module.title}><b>{String(index + 1).padStart(2, "0")}</b><span>{module.title}</span></button>)}<div className="sidebar-note"><b>FERRAMENTAS PRÁTICAS</b><button className={tool ? "tool-link selected" : "tool-link"} onClick={() => setTool(true)}>Checklist Passageiro Pet</button><button className="tool-link" disabled>Cronograma sanitário</button><button className="tool-link" disabled>Quadro-resumo de CVI</button></div></aside><article className="lesson">{tool ? <Checklist checks={checks} setChecks={setChecks} /> : <ModulePage module={current} number={active + 1} />}</article></div></main>;
}
function ModulePage({ module, number }: { module: Module; number: number }) { return <><div className="lesson-meta"><span>MÓDULO {number}</span><span>{module.subtitle}</span></div><h1>{module.title}</h1><p className="lesson-lead">{module.overview}</p><section className="objective"><p>NESTE MÓDULO</p><ul>{module.topics.map(topic => <li key={topic}>{topic}</li>)}</ul></section><h2>Como estudar este conteúdo</h2><p>Leia na sequência, registre as dúvidas e use os materiais operacionais quando a aula pedir aplicação prática. Informações sobre países, prazos, documentos e companhias aéreas devem ser confirmadas nas fontes oficiais vigentes.</p><div className="method"><p>APLICAÇÃO PROFISSIONAL</p><ol><li>Identifique o que se aplica ao caso.</li><li>Consulte a fonte oficial e a companhia aérea.</li><li>Organize os prazos e pendências.</li><li>Documente a conferência antes de orientar o tutor.</li></ol></div><div className="warning"><b>Atenção</b><p>Este módulo é um guia didático. A responsabilidade técnica exige validação atualizada para cada processo real.</p></div></> }
function Checklist({ checks, setChecks }: { checks: boolean[]; setChecks: (values: boolean[]) => void }) { return <><div className="lesson-meta"><span>FERRAMENTA PRÁTICA</span><span>Preparação para a viagem</span></div><h1>Checklist Passageiro Pet</h1><p className="lesson-lead">Organize a conferência antes da viagem e salve a versão preenchida pelo botão de PDF.</p><div className="checklist">{checklist.map((item, index) => <label key={item}><input type="checkbox" checked={checks[index]} onChange={() => setChecks(checks.map((value, position) => position === index ? !value : value))} /><span>{item}</span></label>)}</div><button className="clear" onClick={() => setChecks(checklist.map(() => false))}>Limpar checklist</button><div className="warning"><b>Pontos de atenção</b><p>Confirme os horários de apresentação, requisitos operacionais e a documentação diretamente com a companhia aérea e as autoridades competentes.</p></div></> }
